### ISSUE TITLE
Warning: no short audios found，无法找到短音频。ffmpeg路径、数据集位置、音频长短、命名均符合要求。

### ISSUE THREAD

**Issue by TralMac** [YYuX-1145/Bert-VITS2-Integration-package#17]
Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links.
this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.
会不会是不支持日语的原因？我看源仓库内有提交修复日语的更新。

**Comment by YYuX-1145** [comment]
暂不支持日语，原项目似乎未开发完全并且没有日语底膜

**Comment by YYuX-1145** [comment]
但是我认为日语的表现vits已经足够好。你可以前往vits快速微调。

**Comment by NestuFNG** [comment]
为什么我的音频文件是中文，但也显示no short audios found呢

**Comment by YYuX-1145** [comment]
> 为什么我的音频文件是中文，但也显示no short audios found呢

FFmpeg没有被正确安装
