### ISSUE TITLE
训练时显示ModuleNotFoundError: No module named 'monotonic_align.monotonic_align.core'解决后引发的更多错误

### ISSUE THREAD

**Issue by c469591** [YYuX-1145/Bert-VITS2-Integration-package#26]
你好，
目前我正在尝试自己部属环境，
我在run这个命令时→
python train_ms.py -c ./configs\config.json
他会提示
ModuleNotFoundError: No module named 'monotonic_align.monotonic_align.core'
我用pip安装monotonic_align之后仍然有一样的错误，
需要删除完整包中的monotonic_align才不会报告这个错误，
但继续运行时又显示
ImportError: FFmpeg libraries are not found.Please install FFmpeg.
但我直接在cmd中输入ffmpeg可以看到ffmpeg的版本，且前面的预处理过程也很顺利，
ffmpeg是我自己手动配置的环境变亮，
我的python是3.10，
在一开始安装requirements.txt时有报错，因此我手动按照requirements.txt里面的名字来安装每个包，没有指定版本，
请问这问题该如何解决，谢谢

**Comment by YYuX-1145** [comment]
build monotonic_align的方法参照原版vits

**Comment by c469591** [comment]
请问哪个项目才是vits2原项目？可以提供连接吗？或是提供关于构建monotonic_align的连接？感谢

**Comment by c469591** [comment]
现在已经解决了，要是没有报告
ModuleNotFoundError: No module named 'monotonic_align.monotonic_align.core'
这个包是不是就OK了？
