### ISSUE TITLE
我可以顺利预处理，但训练时显示ImportError: FFmpeg libraries are not found.Please install FFmpeg.

### ISSUE THREAD

**Issue by c469591** [YYuX-1145/Bert-VITS2-Integration-package#28]
你好，请问我已经顺利跑通了预处理以及前面的几个步骤，
现在运行训练命令时他会显示
ImportError: FFmpeg libraries are not found.Please install FFmpeg.
我在cmd输入ffmpeg可以看到ffmpeg的版本输出，ffmpeg是自己配置的系统便亮，
我是windows10、python3.10，这个项目对python版本有要求吗？
谢谢！

**Comment by YYuX-1145** [comment]
我不知道，整合包是3.8.10

**Comment by c469591** [comment]
那请问整合包如何使用呢？
我启动start.bat，但看到的就这样的输出
I:\bert vits2\Bert-VITS2-Integration-Package>
这似乎是我自己的路径而已，并没有看出来他有顺利启动虚拟环境，也没有看到报错，看起来就很奇怪…
我是需要装python3.8才能顺利用这个环境吗？

**Comment by c469591** [comment]
哦我好像顺利跑通了，使用大大的环境，要用
venv\python.exe要运行的命令
这样才能跑起来
