### ISSUE TITLE
数据集重采样和标注·——whisper标注

### ISSUE THREAD

**Issue by TunaSaiko** [YYuX-1145/Bert-VITS2-Integration-package#33]
请问如果我的数据集全部是日语的情况下，
%PYTHON% short_audio_transcribe.py --languages "CJ" --whisper_size large

这里的languages "CJ"是不是改成 languages "J" 就可以？

**Comment by YYuX-1145** [comment]
不是的，主要还是代码懒得改了，语言选项本质也是忽略掉除选定语言外的其他语言。这点在代码里可以看得到，并且不会影响精准度。

**Comment by TunaSaiko** [comment]
> 不是的，主要还是代码懒得改了，语言选项本质也是忽略掉除选定语言外的其他语言。这点在代码里可以看得到，并且不会影响精准度。

原来如此，所以如果训练纯日语模型也按照步骤去就好对吗

**Comment by YYuX-1145** [comment]
> > 不是的，主要还是代码懒得改了，语言选项本质也是忽略掉除选定语言外的其他语言。这点在代码里可以看得到，并且不会影响精准度。
> 
> 原来如此，所以如果训练纯日语模型也按照步骤去就好对吗
对，基本不影响，如果真识别错了可以手动在标注文件中去掉

**Comment by TunaSaiko** [comment]
> > > 不是的，主要还是代码懒得改了，语言选项本质也是忽略掉除选定语言外的其他语言。这点在代码里可以看得到，并且不会影响精准度。
> > 
> > 
> > 原来如此，所以如果训练纯日语模型也按照步骤去就好对吗
> > 对，基本不影响，如果真识别错了可以手动在标注文件中去掉

谢谢大佬！
