### ISSUE TITLE
训练多次时间？

### ISSUE THREAD

**Issue by qiuyuzhao** [YYuX-1145/Bert-VITS2-Integration-package#35]
要训练多久啊。我训练出来的模型推理结果都是滋滋噪音， 没有人声

**Comment by YYuX-1145** [comment]
可能没有加载底膜？底膜微调100步音色就可以贴近

**Comment by qiuyuzhao** [comment]
感谢大佬， 但是我加载了底模， 请问数据量通常应该要多少啊？

**Comment by YYuX-1145** [comment]
实测三分钟就有一定效果。都是噪音肯定不正常。也可能你加载了旧版底膜
