### ISSUE TITLE
更新whisper到V3，但调用whisper失败，需要修改哪个文件已是配channels数量？

### ISSUE THREAD

**Issue by c469591** [YYuX-1145/Bert-VITS2-Integration-package#45]
你好，我已经使用这个命令将完整包的whisper更新到v3
%PYTHON% -m pip install -U openai-whisper
但要调用时显示
Given groups=1, weight of size [1280, 128, 3], expected input[1, 80, 3000] to have 128 channels, but got 80 channels ins
请问需要修改哪个文件已是配V3的128channels
谢谢

**Comment by YYuX-1145** [comment]
https://github.com/openai/whisper/discussions/1778

**Comment by c469591** [comment]
问题解决，感谢大老
