### ISSUE TITLE
多语言的版本训练出的模型变成纯电音，是必须有多语言的语料吗？ 还是其他原因导致的？

### ISSUE THREAD

**Issue by see2023** [YYuX-1145/Bert-VITS2-Integration-package#48]
之前用中日版本(1.1)的脚本处理的素材，训练时发现在第一个Epoch后，就能听到有点对的口音了，但是到100步后电音就很厉害，1000步后就变成电流纯噪声了。

但是相同的素材(包括train.list, val.list)都完全相同，把代码和底模切换到1.0纯中文的最新版本，训练到1000步的效果是很好的。

然后今天试了下中英日2.1版本，素材还是一样，重新执行了bert_gen.py，新增执行了emo_gen.py，训练时和1.1一样很快就变成电音了。

请问是必须有多语言的素材，还是配置文件或者其他方面有错误呢？

**Comment by YYuX-1145** [comment]
list里的路径是否已经修改？训练产生的bert.pt和spec.pt是否手动删除了？

**Comment by see2023** [comment]
train.list, val.list 里的路径是对的，打日志看了
bert删掉重新生成过，不删的话训练会崩掉，2.1用的bert数据结构不一样了
spec.pt也删掉重新跑过了。
配置文件只改了 batch_size  n_speakers 和 *interval 这几个参数。
如果把learning_rate改小一点，电音化出现会慢一些，但是到1000个step也完全是电音了。

你的意思是如果只有中文素材，用2.1版本也是可以训练出三种语音吗？ 或者至少可以训练出中文语音？

**Comment by see2023** [comment]
另外，从日志看，除了前两个loss在逐步下降，后4个都不太稳定，忽高忽低。
麻烦分析下可能是什么原因，我理解的是如果是数据的原因，那1.0版本应该也训练不出好的效果。

INFO:models:[3.0577645301818848, 1.6445229053497314, 8.82172207639087e-06, 0.30810436606407166, 2.4571661949157715, 0.34707584977149963, 400, 9.985010869926718e-07]


INFO:models:[3.0507473945617676, 1.580500841140747, 1.3504314665624406e-05, 0.5576550364494324, 2.7154059410095215, 0.1224212646484375, 600, 9.9770258560352e-07]

**Comment by YYuX-1145** [comment]
应该是load_wav_to_torch的问题，我的整合包用的是torchaudio，就不会有问题，现在我的仓库还没有更新，这些代码我都没改过

**Comment by see2023** [comment]
非常感谢！确实是这里的问题， 把 load_wav_to_torch 换成torchaudio.load就正常了。

测试了下两种方法的返回，如果没有下面这一行的话，返回结果是一样的。
那是这里的normalization处理不合适？
audio_norm = audio / self.max_wav_value

**Comment by YYuX-1145** [comment]
几个月前我第一次用这个项目时scipy发了个警告读取不正常，有可能是这个依赖的问题。归一化处理的这2条代码原版vits就有。vits-fast-fine-tuning的代码里没有audio_norm = audio / self.max_wav_value和audio_norm = audio_norm.unsqueeze(0)，并且torchaudio默认会normalize，因此应该不需要再单独做归一化处理

**Comment by see2023** [comment]
补充一下，虽然能够训练出正常音色了，但是多语言版本有种怪怪的口音，也不是老外口音，有点像南方人说普通话的感觉，但是1.0就明显好很多

**Comment by YYuX-1145** [comment]
就我而言2.1版只训中文的话训的步数比1.0版要多不少

**Comment by Asa-Dong** [comment]
> 应该是load_wav_to_torch的问题，我的整合包用的是torchaudio，就不会有问题，现在我的仓库还没有更新，这些代码我都没改过

感谢+1 遇到了同样的问题 改了之后就好了。

**Comment by tuotuoshao** [comment]
> 非常感谢！确实是这里的问题， 把 load_wav_to_torch 换成torchaudio.load就正常了。
> 
> 测试了下两种方法的返回，如果没有下面这一行的话，返回结果是一样的。 那是这里的normalization处理不合适？ audio_norm = audio / self.max_wav_value

我也碰到同样的问题，相信改了之后也能解决，正在训练中。

但是看完你们的对话还是没理解为什么改了之后是可以的。因为这两种写法如果返回结果是一样的话那为啥一个可以一个不可以？理论上这两种写法返回也应该一致，都是读取然后做一次归一化。

所以我简单测了两段音频，对于48000hz的音频返回是一致的，对于44100的返回值是不一样的。所以这两种返回是不能保证一样的，必须采用torchaudio对吧
![捕获](https://github.com/YYuX-1145/Bert-VITS2-Integration-package/assets/51219602/7671c96a-ef54-430a-adc9-f80ec8a32e19)

**Comment by tuotuoshao** [comment]
又测了下，上面提到的两个赫兹的音频产生不同的结果，其实是因为一个音频已经是归一化了的一个是没有归一化的。所以如果用load_wav_to_torch然后手动归一化会出问题，因为没有判断音频是否是归一化的。而torchaudio里面应该是有判断的，如果是归一化的它不会再去除那个数(32768）。反正根据这两段音频测试结果我是这么猜测的。
