### ISSUE TITLE
大佬求解，文本预处理的

### ISSUE THREAD

**Issue by XU-1-max** [YYuX-1145/Bert-VITS2-Integration-package#49]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine- tuned or trained .Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained .Some weights of EmotionModel were not initialized from the model checkpoint at . 1 emotional/ wav2vec2-large -robust- 12-ft-emotion-msp-dim and are newly initialized: [ ' wav2vec2. encoder . pos conv _ embed . conv . parametrizations .weight. original1' ,'wav2vec2. encoder . pos - conv_ embed . conv . parametrizations . weight . original0']

You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference

Building prefix dict from the default dictionary

Loading model from cache с: Users WuXulAppDataLocalTempljieba . cache ,

Loading model cost 0.280 seconds .

Prefix dict has been built successfully

**Comment by XU-1-max** [comment]
但可以正常训练，但几分钟就训练完了，训练参数没问题

**Comment by YYuX-1145** [comment]
看上去是正常的
