### ISSUE TITLE
开始训练时的新问题 页面文件太小

### ISSUE THREAD

**Issue by Slldyd2077** [YYuX-1145/Bert-VITS2-Integration-package#5]
刚开始用大数据集的时候会和上一位题主一样出现除零错误，那个issues用换小数据集的方法解决后又出现了新的报错
**OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "D:\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.**
不知所措QaQ

**Comment by YYuX-1145** [comment]
我猜测是内存不足导致的。把train.py的num_workers调小，调到2甚至为0

**Comment by YYuX-1145** [comment]
> 我猜测是内存不足导致的。把train.py的num_workers调小，调到2甚至为0

打开文本编辑器或编程软件按ctrl+f快速找到这个变量哈
