### ISSUE TITLE
会像vits那样训练多人的时候相互影响吗

### ISSUE THREAD

**Issue by tuotuoshao** [YYuX-1145/Bert-VITS2-Integration-package#53]
比如一个正常语速一个emo电台语速两种数据训练两个人，推理的时候会发现正常语速的都会时不时停顿，明显没有单独训练效果好

**Comment by YYuX-1145** [comment]
测下来是会的

**Comment by tuotuoshao** [comment]
也不能追加训练吗，就是先训几个人，后面发现漏了一个人，再去追加训练，原先的人是不是也会被后面那个人的数据覆盖或者说影响了。
在vits那边看到这样一句话all old speakers will be cleared and your designated speakers will be added in instead.所以bert-vits2也一样？
那么最好的训练方式是不是一次训练多个人并且这些人语速等都差不多。或者单独训练这n个人得到n个模型，这样就不要求语速等一致了？

**Comment by YYuX-1145** [comment]
不能追加训练。没错。
