### ISSUE TITLE
继续训练的一些问题

### ISSUE THREAD

**Issue by that9527** [YYuX-1145/Bert-VITS2-Integration-package#55]
请问怎么继续训练之前训练到一半的模型呢？
继续训练出的模型推理出来是混乱的纯电音，还能回溯之前训练的模型吗？

**Comment by YYuX-1145** [comment]
帮助里有提到，2.3的代码没改过不要用。推理出来是混乱的纯电音，说明训练没有正常运行。

**Comment by ziyuan666** [comment]
> 帮助里有提到，2.3的代码训练没改过不要用。推理出来是打乱的纯电音，说明没有正常运行。The help mentioned, 2.3 code has not changed do not use. The inference was that it was a chaotic pure electric sound, indicating that the training was not working properly.

这种情况一开始是正常模型，但是继续跑变成电音，也没存档了咋办呢请问一下，然后重新跑也变成电音了
