### ISSUE TITLE
使用已有模型时遇到的问题

### ISSUE THREAD

**Issue by dqsans** [YYuX-1145/Bert-VITS2-Integration-package#56]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "webui.py", line 382, in <module>
    net_g = get_net_g(
  File "F:\2.3\Bert-VITS2-2.3\Bert-VITS2-2.3\infer.py", line 88, in get_net_g
    n_speakers=hps.data.n_speakers,
AttributeError: 'HParams' object has no attribute 'n_speakers'

F:\2.3\Bert-VITS2-2.3\Bert-VITS2-2.3>

**Comment by YYuX-1145** [comment]
检查使用的配置文件是否正确？
