### ISSUE TITLE
开始训练时问题(数据集已在raw内)

### ISSUE THREAD

**Issue by dqsans** [YYuX-1145/Bert-VITS2-Integration-package#57]
Enter a letter to choose language.

C = Chinese ; J = Japanese ;E = English;
 e.g: C

Enter language: C
transcribe error. len(speaker_annos) == 0

**Comment by YYuX-1145** [comment]
启动命令行，依次输入：
```
cd Data
tree /f
```
结果发出来，否则问题是无效的

**Comment by lsCoding666** [comment]
音频要存放在角色文件夹下面 你得在里面再新建文件夹
