### ISSUE TITLE
train

### ISSUE THREAD

**Issue by aotutud** [YYuX-1145/Bert-VITS2-Integration-package#59]
The 2.3 version trains Chinese with a hint of English, which is only suitable for English training. I tried not to add SLM to the training, but there is no English feeling anymore, but there is a hint of Japanese and robot flavors inside

**Comment by YYuX-1145** [comment]
The performance of the model can be significantly influenced by the dataset. Therefore, it is important to assess the quality and size of the dataset and ensure the accuracy of labeling. Additionally, attention should be given to the training parameters. If you are unsatisfied with the performance of version 2.3, you may consider trying version 2.1 (which supports CJE) or version 1.0 (Chinese only).

**Comment by aotutud** [comment]
> The performance of the model can be significantly influenced by the dataset. Therefore, it is important to assess the quality and size of the dataset and ensure the accuracy of labeling. Additionally, attention should be given to the training parameters. If you are unsatisfied with the performance of version 2.3, you may consider trying version 2.1 (which supports CJE) or version 1.0 (Chinese only).数据集可能会对模型的性能产生重大影响。因此，评估数据集的质量和大小并确保标注的准确性非常重要。此外，还应注意训练参数。如果你对2.3版本的性能不满意，可以考虑尝试2.1版本（支持CJE）或1.0版本。

Ok，I'm trying
