### ISSUE TITLE
训练总是空跑

### ISSUE THREAD

**Issue by wuzhengxuan** [YYuX-1145/Bert-VITS2-Integration-package#60]
音频是15s一个文件
格式是FormatFactoryPart1
文本预处理和生成bert都成功了，但是训练总是空跑，信息如下

加载config中的配置0
加载config中的配置localhost
加载config中的配置10086
加载config中的配置0
加载config中的配置1
加载环境变量
MASTER_ADDR: localhost,
MASTER_PORT: 10086,
WORLD_SIZE: 1,
RANK: 0,
LOCAL_RANK: 0
01-01 22:51:58 INFO     | data_utils.py:63 | Init dataset...
100%|███████████████████████████████████████████████████████████████████████████████| 97/97 [00:00<00:00, 96226.94it/s]
01-01 22:51:58 INFO     | data_utils.py:78 | skipped: 77, total: 97
Bucket warning
01-01 22:51:58 INFO     | data_utils.py:63 | Init dataset...
100%|████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]
01-01 22:51:58 INFO     | data_utils.py:78 | skipped: 3, total: 4
Using noise scaled MAS for VITS2
Using duration discriminator for VITS2
INFO:models:Loaded checkpoint 'Data\xybb\models\DUR_0.pth' (iteration 0)
ERROR:models:emb_g.weight is not in the checkpoint
INFO:models:Loaded checkpoint 'Data\xybb\models\G_0.pth' (iteration 0)
INFO:models:Loaded checkpoint 'Data\xybb\models\D_0.pth' (iteration 0)
******************检测到模型存在，epoch为 1，gloabl step为 0*********************
INFO:models:Loaded checkpoint 'Data\xybb\models\WD_0.pth' (iteration 0)
Some weights of the model checkpoint at ./slm/wavlm-base-plus were not used when initializing WavLMModel: ['encoder.pos_conv_embed.conv.weight_g', 'encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing WavLMModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing WavLMModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of WavLMModel were not initialized from the model checkpoint at ./slm/wavlm-base-plus and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
0it [00:07, ?it/s]
INFO:models:====> Epoch: 0
0it [00:00, ?it/s]
INFO:models:====> Epoch: 1
0it [00:00, ?it/s]
INFO:models:====> Epoch: 2
0it [00:00, ?it/s]
INFO:models:====> Epoch: 3

请问该如何是好

**Comment by YYuX-1145** [comment]
被跳过了那么多，数据集有大问题

**Comment by wuzhengxuan** [comment]
> 被跳过了那么多，数据集有大问题

您是指音频的格式有问题？还是？我看文本预处理的信息大部分都是对的

**Comment by YYuX-1145** [comment]
数据集质量，包括标注和清晰度等 被跳那么多条说明数据集制备有问题

**Comment by wuzhengxuan** [comment]
> 数据集质量，包括标注和清晰度等 被跳那么多条说明数据集制备有问题

明白了，我再整理整理，非常感谢
