### ISSUE TITLE
venv\python.exe执行失败提示“系统找不到指定的路径”

### ISSUE THREAD

**Issue by GhostXia** [YYuX-1145/Bert-VITS2-Integration-package#62]
明白是没有内置venv了。主要是不知道缺什么模块，我手动运行后，跟着报错提示一个一个装，还是在疯狂报错。

**Comment by YYuX-1145** [comment]
你是自己配的环境？用-d启动管理器指定Python解释器路径
例如 manager230.exe -d python

**Comment by GhostXia** [comment]
成了，跑起来了。
