### ISSUE TITLE
训练失败

### ISSUE THREAD

**Issue by Electrify27** [YYuX-1145/Bert-VITS2-Integration-package#68]
加载config中的配置0
加载config中的配置localhost
加载config中的配置10086
加载config中的配置0
加载config中的配置1
加载环境变量
MASTER_ADDR: localhost,
MASTER_PORT: 10086,
WORLD_SIZE: 1,
RANK: 0,
LOCAL_RANK: 0
01-14 13:04:01 INFO     | data_utils.py:63 | Init dataset...
0it [00:00, ?it/s]
01-14 13:04:01 INFO     | data_utils.py:78 | skipped: 0, total: 0
Bucket warning
01-14 13:04:01 INFO     | data_utils.py:63 | Init dataset...
100%|████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<?, ?it/s]
01-14 13:04:01 INFO     | data_utils.py:78 | skipped: 0, total: 2
Using noise scaled MAS for VITS2
Using duration discriminator for VITS2
INFO:models:Loaded checkpoint 'Data\Yennefer\models\DUR_0.pth' (iteration 0)
ERROR:models:emb_g.weight is not in the checkpoint
INFO:models:Loaded checkpoint 'Data\Yennefer\models\G_0.pth' (iteration 0)
INFO:models:Loaded checkpoint 'Data\Yennefer\models\D_0.pth' (iteration 0)
******************检测到模型存在，epoch为 1，gloabl step为 0*********************
INFO:models:Loaded checkpoint 'Data\Yennefer\models\WD_0.pth' (iteration 0)
Some weights of the model checkpoint at ./slm/wavlm-base-plus were not used when initializing WavLMModel: ['encoder.pos_conv_embed.conv.weight_v', 'encoder.pos_conv_embed.conv.weight_g']
- This IS expected if you are initializing WavLMModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing WavLMModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of WavLMModel were not initialized from the model checkpoint at ./slm/wavlm-base-plus and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'encoder.pos_conv_embed.conv.parametrizations.weight.original0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
0it [00:00, ?it/s]
INFO:models:====> Epoch: 0
0it [00:02, ?it/s]
INFO:models:====> Epoch: 1
0it [00:00, ?it/s]
INFO:models:====> Epoch: 2
0it [00:00, ?it/s]
INFO:models:====> Epoch: 3
0it [00:00, ?it/s]
INFO:models:====> Epoch: 4
0it [00:00, ?it/s]
INFO:models:====> Epoch: 5
0it [00:00, ?it/s]
INFO:models:====> Epoch: 6
0it [00:00, ?it/s]
INFO:models:====> Epoch: 7
0it [00:00, ?it/s]
INFO:models:====> Epoch: 8
0it [00:00, ?it/s]
INFO:models:====> Epoch: 9
0it [00:00, ?it/s]
INFO:models:====> Epoch: 10

**Comment by Electrify27** [comment]
下头就直接快速跑完设置的步数后就没了 模型也没跑出来

**Comment by YYuX-1145** [comment]
```
01-14 13:04:01 INFO | data_utils.py:63 | Init dataset...
0it [00:00, ?it/s]
01-14 13:04:01 INFO | data_utils.py:78 | skipped: 0, total: 0
```
你就说你有没有训练集吧
