### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by bearatm** [YYuX-1145/Bert-VITS2-Integration-package#76]
INFO:models:Loaded checkpoint 'Data\Airi\models\G_0.pth' (iteration 0)
INFO:models:Loaded checkpoint 'Data\Airi\models\D_0.pth' (iteration 0)
******************检测到模型存在，epoch为 1，gloabl step为 0*********************
  0%|                                                                                           | 0/11 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "train_ms.py", line 834, in <module>
    run()
  File "train_ms.py", line 369, in run
    train_and_evaluate(
  File "train_ms.py", line 595, in train_and_evaluate
    loss_gen_all += loss_dur_gen + loss_lm + loss_lm_gen
UnboundLocalError: local variable 'loss_lm' referenced before assignment

请问报这个错该怎么处理，替换了clap版本的

**Comment by YYuX-1145** [comment]
我不知道你说的clap指的是哪个发行版本，非本仓库的代码没有被我验证过可能是有bug的
